USE EMPLOYEES;
CREATE TABLE CUSTOMERS
(
CUSTOMER_ID INT AUTO_INCREMENT,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
EMAIL_ID VARCHAR(255),
COMPLAINT INT(15),
PRIMARY KEY (CUSTOMER_ID)
);

ALTER TABLE CUSTOMERS
ADD COLUMN GENDER  ENUM('M','F') AFTER LAST_NAME;

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME,LAST_NAME,GENDER,EMAIL_ID,COMPLAINT)
VALUES(002,'JOHN', 'SNOW', 'M', 'JSNOW@GMAIL.COM', 0), (003,'TAUFEEQ', 'MALIK', 'M', 'TMALIK@GMAIL.COM', 0),(004,'RASHIDA', 'KHALIL', 'F', 'RASHIDA2@GMAIL.COM', 5);


SELECT * FROM CUSTOMERS;


